# Use an official Python runtime as a base image
FROM python:latest

#Create working directory
RUN mkdir -p /usr/src/Assignment1

# Set the working directory to /usr/src/Assignment1
WORKDIR /usr/src/Assignment1

# Copy the current directory contents into the container at /usr/src/Assignment1
COPY *.txt *.py *.json *.sh /usr/src/Assignment1/

# Bundle Assignment1 source
COPY . /usr/src/Assignment1

# Install any needed packages specified in requirements.txt
RUN pip install -r requirements.txt
RUN pip install jupyter notebook

# Make port 80 available to the world outside this container
EXPOSE 80

# Define environment variable
#ENV NAME World

# Run app.py when the container launches
CMD ["./run.sh"]
#RUN /run.sh